#!/usr/bin/env bash

if [[ -s "/usr/local/rvm/environments/ruby-1.8.6-p420" ]]
then
  source "/usr/local/rvm/environments/ruby-1.8.6-p420"
  exec rdoc "$@"
else
  echo "ERROR: Missing RVM environment file: '/usr/local/rvm/environments/ruby-1.8.6-p420'" >&2
  exit 1
fi
  