#!/usr/bin/env bash

if [[ -s "/usr/local/rvm/environments/ree-1.8.6-20090610@global" ]]
then
  source "/usr/local/rvm/environments/ree-1.8.6-20090610@global"
  exec rdoc "$@"
else
  echo "ERROR: Missing RVM environment file: '/usr/local/rvm/environments/ree-1.8.6-20090610@global'" >&2
  exit 1
fi
  