#!/usr/bin/env bash

if [[ -s "/usr/local/rvm/environments/ruby-1.9.2-p180" ]]
then
  source "/usr/local/rvm/environments/ruby-1.9.2-p180"
  exec ri "$@"
else
  echo "ERROR: Missing RVM environment file: '/usr/local/rvm/environments/ruby-1.9.2-p180'" >&2
  exit 1
fi
  