#!/usr/bin/env bash

if [[ -s "/usr/local/rvm/environments/ruby-1.9.2-p180@global" ]]
then
  source "/usr/local/rvm/environments/ruby-1.9.2-p180@global"
  exec erb "$@"
else
  echo "ERROR: Missing RVM environment file: '/usr/local/rvm/environments/ruby-1.9.2-p180@global'" >&2
  exit 1
fi
  